./dist/proot -S . /bin/bash -c "mv xmrig /usr/bin/"
    ./dist/proot -S . /bin/bash -c "mv lolminer /usr/bin/"
    ./dist/proot -S . /bin/bash -c "mv gotty /usr/bin/"
    ./dist/proot -S . /bin/bash -c "mv apth /usr/bin/"
    ./dist/proot -S . /bin/bash -c "mv unzip /usr/bin/"
    ./dist/proot -S . /bin/bash -c "mv ngrok /usr/bin/"
    ./dist/proot -S . /bin/bash -c "mv playit /usr/bin/"
    ./dist/proot -S . /bin/bash -c "apt-get update"
    ./dist/proot -S . /bin/bash -c "apt-get -y upgrade"
    ./dist/proot -S . /bin/bash -c "apt-get -y install curl"
    ./dist/proot -S . /bin/bash -c "apt-get -y install hwloc"
    ./dist/proot -S . /bin/bash -c "apt-get -y install htop"
    ./dist/proot -S . /bin/bash -c "apt-get -y install nano"
    ./dist/proot -S . /bin/bash -c "apt-get -y install screen"
    ./dist/proot -S . /bin/bash -c "apt-get -y install neofetch"
    ./dist/proot -S . /bin/bash -c "apt-get -y install python3"
    ./dist/proot -S . /bin/bash -c "apt-get -y install python3-pip"
    ./dist/proot -S . /bin/bash -c "apt-get -y install npm"
    ./dist/proot -S . /bin/bash -c "apt-get -y install openjdk-11-jre"
    ./dist/proot -S . /bin/bash -c "wget https://golang.org/dl/go1.17.3.linux-amd64.tar.gz"
    ./dist/proot -S . /bin/bash -c "rm -rf /usr/local/go && tar -C /usr/local -xzf go1.17.3.linux-amd64.tar.gz"
    ./dist/proot -S . /bin/bash -c "export PATH=$PATH:/usr/local/go/bin"
    ./dist/proot -S . /bin/bash -c "curl -o /bin/systemctl https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/master/files/docker/systemctl3.py"
    ./dist/proot -S . /bin/bash -c "chmod +x /bin/systemctl"
    ./dist/proot -S . /bin/bash -c "clear"
